name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Debug workspace
      run: ls -R
      
    #In case you do not want to use defaults, you for example want to use different template
    - name: Generating HTML from my AsyncAPI document
      uses: asyncapi/github-action-for-cli@v3.1.1 # You can use any version you want
      with:
          filepath: 'asyncapi.yaml'
          output: './docs'
          
    - name: Upload AsyncAPI Docs
      uses: actions/upload-artifact@v3
      with:
        name: asyncapi-docs
        path: './docs'
